apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rpi-metrics-pvc
  namespace: rpi-metrics
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}

