apiVersion: v1
kind: Service
metadata:
  name: rpi-metrics-collector-service
  namespace: rpi-metrics
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
  selector:
    app: rpi-metrics-collector

